# Generated by Django 5.0.1 on 2024-02-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=50)),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
                ('feedback', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='studentdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('joiningdate', models.DateField()),
                ('duration', models.DurationField()),
                ('rollno', models.IntegerField(max_length=10)),
            ],
        ),
    ]
